package com.study.spring.springweb.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: t_coffee
 */
public class Coffee implements Serializable {
    /**
     * Table:     t_coffee
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * Table:     t_coffee
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * Table:     t_coffee
     * Column:    price
     * Nullable:  false
     */
    private Long price;

    /**
     * Table:     t_coffee
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * Table:     t_coffee
     * Column:    update_time
     * Nullable:  true
     */
    private Date updateTime;

    /**
     * 商城跟支付宝交互的流水号
     *
     * Table:     t_coffee
     * Column:    for_ali_num
     * Nullable:  true
     */
    private String forAliNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_coffee
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffee.id
     *
     * @return the value of t_coffee.id
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffee.id
     *
     * @param id the value for t_coffee.id
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffee.name
     *
     * @return the value of t_coffee.name
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffee.name
     *
     * @param name the value for t_coffee.name
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffee.price
     *
     * @return the value of t_coffee.price
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffee.price
     *
     * @param price the value for t_coffee.price
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffee.create_time
     *
     * @return the value of t_coffee.create_time
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffee.create_time
     *
     * @param createTime the value for t_coffee.create_time
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffee.update_time
     *
     * @return the value of t_coffee.update_time
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffee.update_time
     *
     * @param updateTime the value for t_coffee.update_time
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffee.for_ali_num
     *
     * @return the value of t_coffee.for_ali_num
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public String getForAliNum() {
        return forAliNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffee.for_ali_num
     *
     * @param forAliNum the value for t_coffee.for_ali_num
     *
     * @mbg.generated Mon Apr 08 16:56:36 CST 2019
     */
    public void setForAliNum(String forAliNum) {
        this.forAliNum = forAliNum == null ? null : forAliNum.trim();
    }
}